### ISSUE TITLE
Catch Exceptions

### ISSUE THREAD

**Issue by sharpy66** [Galaxypedia-Wiki/GalaxyGPT#76]
Especially in AiClient.cs where prompts that fail the moderation check will currently take the rest of the program down with them. 

It would also be ideal to implement catches as necessary throughout the wider code-base.

**Comment by smallketchup82** [comment]
not sure if this should be in this repo.

the reason why there is no catches in `AiClient` is because exceptions should go up the call stack into the [ASP.NET endpoint](https://github.com/Galaxypedia-Wiki/GalaxyGPT/blob/293d925ecf243fae69c9e4ac1d81d6e3f975af0e/galaxygpt-api/Program.cs#L122)

by handling the exceptions there, the api endpoint will automatically return an error 500.

i'm more keen on transferring this to ketchupbot-discord
